# Generated by Django 4.0.1 on 2022-03-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_itemform_managefunds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemform',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
