# Generated by Django 4.0.1 on 2022-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
